### ISSUE TITLE
Wrong preprocessor define mentioned in README?

### ISSUE THREAD

**Issue by hsnabn** [tinfoilboy/mcv#1]
The README mentions that `_MCV_COMMAND_LINE_COMPILE` needs to be a preprocessor define for the command line tool to correctly compile.

However, the actual define that is used appears to be ` _MCV_COMPILE_COMMAND_LINE`.

Side note: mcv compiles using TDM-GCC 5.1.0 on Windows. There's some warnings, though. I used the `-Wall` option for warnings. I haven't tested the application, though.

**Comment by tinfoilboy** [comment]
Thank you! I'll go change the README right now.

Also, could you show me the warnings that you get? At least in my dev environment, I use /W4 (warning level 4, all warnings is useless in VC++) flag as well as /WX (treat warnings as errors). If you show me the warnings, I'll attempt to get them fixed up? Unless you want to fix them.

**Comment by hsnabn** [comment]
Sure, here's my warning log:

```
||=== Build: Debug in mcv (compiler: TDM-GCC-64 Compiler) ===|

mcv\data_types.h|24|warning: inline function 'mcv_texture_coordinate_equal' declared but never defined|

mcv\data_types.h|15|warning: inline function 'mcv_position_equal' declared but never defined|

* mcv\data_types.c||In function 'mcv_load_pair_def':

mcv\data_types.c|107|warning: argument to 'sizeof' in 'memset' call is the same expression as the destination; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]|

* mcv\data_types.c||In function 'mcv_load_triplet_def':

mcv\data_types.c|154|warning: argument to 'sizeof' in 'memset' call is the same expression as the destination; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]|

mcv\data_types.c|128|warning: variable 'tempSize' set but not used [-Wunused-but-set-variable]|

mcv\data_types.h|24|warning: inline function 'mcv_texture_coordinate_equal' declared but never defined|

mcv\data_types.h|15|warning: inline function 'mcv_position_equal' declared but never defined|

mcv\data_types.h|24|warning: inline function 'mcv_texture_coordinate_equal' declared but never defined|

mcv\data_types.h|15|warning: inline function 'mcv_position_equal' declared but never defined|

* mcv\loaders\obj_load.c||In function 'mcv_count_obj_amounts':

mcv\loaders\obj_load.c|34|warning: statement with no effect [-Wunused-value]|

mcv\data_types.h|24|warning: inline function 'mcv_texture_coordinate_equal' declared but never defined|

mcv\data_types.h|15|warning: inline function 'mcv_position_equal' declared but never defined|

mcv\data_types.h|24|warning: inline function 'mcv_texture_coordinate_equal' declared but never defined|

mcv\data_types.h|15|warning: inline function 'mcv_position_equal' declared but never defined|

||=== Build finished: 0 error(s), 14 warning(s) (0 minute(s), 0 second(s)) ===|
```

These are just the warnings, if you need the full build log, ask me. I tried to format it so as to make it easier to read.

 I don't really know much C, but these may be only triggered due to GCC and MSVC compilers doing some things differently, so it may not be possible to fix them.

**Comment by tinfoilboy** [comment]
@hsnabn

Well, in the latest revision, I (hopefully) fixed the warnings. I had accidentally set a few of the `data_types.h` functions to inline, but never actually used them as inline. Also, that `mcv_count_obj_amounts` warning is actually pretty bad. Basically, it never counted the amount of texture coordinates in the model, so therefore, it would report zero.

Things like this is why I usually turn on warnings as errors, I'm surprised VS didn't pick it up.

**Comment by hsnabn** [comment]
I just compiled it again under fixed version, and the compiler doesn't give off any warnings under `-Wall` now.

Congratulations! (I guess?)

**Comment by tinfoilboy** [comment]
@hsnabn 

Hmm, strangely enough I have warning level 4 on, yet I still never got the warning for that. Either way, it's fixed now!
